server:
    #定义端口号
  port: 7001
spring:
  application:
    #定义应用名称，即服务名称
    name: admanagement-consumer-server
    #数据库信息配置
  datasource:
    url: jdbc:mysql://localhost:3306/loongcheer?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka
    register-with-eureka: false

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.loongcheer.advertisement.admanagementconsumer.service.AdPlacementFeignService: debug

